---
- name: Get details of virtual machine to be replicated
  azure_rm_virtualmachine_info:
    resource_group: "{{ az_rg_name }}"
    name: "{{ az_vm_name }}"
  register: var_vm_info

#- raw: Get-AzVM -ResourceGroupName "{{ az_rg_name }}" -Name "{{ az_vm_name }}"
#  register: var_vm_info

- debug:
    msg: "{{ var_vm_info }}"
...